#!/bin/bash
set -eu

cd "$(dirname "$0")/.."

scripts/download mji.00601-xlsx.zip
mkdir -p resources
unzip -o cache/mji.00601-xlsx.zip -d resources/mji
npx ts-node scripts/xlsx2csv.ts resources/mji/mji.00601.xlsx resources/mji/mji.00601.csv
