"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.openDatabaseFromUrl = exports.openDatabaseFromFile = exports.getSqlJsWeb = exports.getSqlJsNode = exports.createSqlJsExecutor = exports.createMojidataDbProvider = void 0;
var sqljs_1 = require("./internal/adapter/sqljs");
Object.defineProperty(exports, "createMojidataDbProvider", { enumerable: true, get: function () { return sqljs_1.createMojidataDbProvider; } });
Object.defineProperty(exports, "createSqlJsExecutor", { enumerable: true, get: function () { return sqljs_1.createSqlJsExecutor; } });
Object.defineProperty(exports, "getSqlJsNode", { enumerable: true, get: function () { return sqljs_1.getSqlJsNode; } });
Object.defineProperty(exports, "getSqlJsWeb", { enumerable: true, get: function () { return sqljs_1.getSqlJsWeb; } });
Object.defineProperty(exports, "openDatabaseFromFile", { enumerable: true, get: function () { return sqljs_1.openDatabaseFromFile; } });
Object.defineProperty(exports, "openDatabaseFromUrl", { enumerable: true, get: function () { return sqljs_1.openDatabaseFromUrl; } });
